package org.engrave.packup.worker

const val DATA_EXCEPTION_MESSAGE_FIELD = "DATA_EXCEPTION_MESSAGE_FIELD"
const val DATA_SUCCEED_PROCESSED_NUMBER_FIELD = "DATA_SUCCEED_PROCESSED_NUMBER_FIELD"

const val DATA_PROGRESS_FIELD = "DATA_SUCCEED_PROCESSED_NUMBER"